version: "3.7"

services:
  database:
    image: mysql:8.0
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always

  load-python:
    image: load-python
    build: images/load-python
    volumes:
      - ./data:/data

  summary-python:
    image: summary-python
    build: images/summary-python
    volumes:
      - ./data:/data
